# Generated by Django 3.1.5 on 2021-01-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_auto_20210109_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvstructure',
            name='technology',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
